### ISSUE TITLE
Getting a Error: Purging failed with the status code 200.

### ISSUE THREAD

**Issue by motion-work** [ayeressian/bunnycdn-storage-deploy#27]
I am getting a `Error: Purging failed with the status code 200.`

<img width="690" alt="Screenshot 2023-01-23 at 19 29 26" src="https://user-images.githubusercontent.com/11538632/214120500-8b2de787-a084-4cf6-b1d3-1078f7c2edd6.png">

here is my config:
```yml
- name: Deploy to BunnyCDN
  uses: ayeressian/bunnycdn-storage-deploy@v1.1.1
  with:
    source: "./output/public"
    storageZoneName: my-storage-zone-name
    accessKey: "${{ secrets.PROD_STORAGE_KEY }}"
    pullZoneId: 1156109
    pullZoneAccessKey: "${{ secrets.PROD_PULL_ZONE_KEY }}"
    remove: "true"
    purge: "true"
```

anyone can help?
