### ISSUE TITLE
Warning: Unexpected input(s) 'upload' in v2.0.2

### ISSUE THREAD

**Issue by jansroka** [ayeressian/bunnycdn-storage-deploy#37]
I am using this code (per the current README) in my action:

```
 - name: Deploy to BunnyCDN
        uses: ayeressian/bunnycdn-storage-deploy@v2.0.2
        with:
          # Folder to deploy
          source: "dist"
          storageZoneName: "${{ secrets.BUNNY_STORAGE_ZONE_NAME }}"
          storagePassword: "${{ secrets.BUNNY_STORAGE_PASSWORD }}"
          # Can be found on https://dash.bunny.net/account/settings
          accessKey: "${{ secrets.BUNNY_API_ACCESS_KEY }}"
          # Get this via API, e.g. here: https://docs.bunny.net/reference/pullzonepublic_index 
          pullZoneId: "${{ secrets.BUNNY_PULL_ZONE_ID }}"
          upload: "true"
          remove: "true"
          purgePullZone: "true"
```

It appears to fully work (no errors on uploads, no error messages), but I get this warning in my github action log:
![Screenshot 2023-05-29 at 21 12 05](https://github.com/ayeressian/bunnycdn-storage-deploy/assets/6746809/bb8f2e05-2a1c-4c41-8ae4-7fa712da8f5f)

Not sure about the impact, this look like a tiny (?) fix to me.
