### ISSUE TITLE
Action fails with unknown error message

### ISSUE THREAD

**Issue by shafy** [ayeressian/bunnycdn-storage-deploy#48]
When trying to run the action, it looks like it starts uploading files but then fails with just printing the whole content `dist/index.js` to the console. There is no specific error message thrown as far as I can tell:

![CleanShot 2024-02-04 at 18 18 20@2x](https://github.com/ayeressian/bunnycdn-storage-deploy/assets/1881676/57f9149a-ba94-4690-998e-5ac6aeb7c53c)

My workflow file:

```yml
name: Deploy to BunnyCDN

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Build Tailwind
        run: |
          npx --yes tailwindcss -i ./assets/css/tailwind.css -o ./_site/assets/css/tailwind.css
      - name: Build Jekyll
        run: |
          JEKYLL_ENV=production bundle exec jekyll build
      - name: Deploy to BunnyCDN
        uses: ayeressian/bunnycdn-storage-deploy@v2.2.0
        with:
          source: "_site"
          destination: "www"
          storageZoneName: ${{ secrets.BUNNY_STORAGE_NAME }}
          storagePassword: ${{ secrets.BUNNY_STORAGE_PASSWORD }}
          storageEndpoint: "storage.bunnycdn.com"
          accessKey: ${{ secrets.BUNNY_API_KEY }}
          pullZoneId: ${{ secrets.BUNNY_ZONE_ID }}
          upload: "true"
          remove: "false"
          purgePullZone: "true"
```

Any ideas?
