### ISSUE TITLE
Update node version (16 is deprecated)

### ISSUE THREAD

**Issue by alexandersandberg** [ayeressian/bunnycdn-storage-deploy#50]
Thanks for creating this action! Works perfectly.

Just wanted to add an issue for this warning that I saw.

>Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: ayeressian/bunnycdn-storage-deploy@v2.2.1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

This is my workflow file:

```
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: ayeressian/bunnycdn-storage-deploy@v2.2.1
        with:
          source: ""
          destination: ""
          storageZoneName: "${{ secrets.BUNNY_STORAGE_NAME }}"
          storagePassword: "${{ secrets.BUNNY_STORAGE_PASSWORD }}"
          accessKey: "${{ secrets.BUNNY_API_KEY }}"
          pullZoneId: "${{ secrets.BUNNY_PULL_ID }}"
          upload: "true"
          remove: "true"
          purgePullZone: "true"

```
